### ISSUE TITLE
Config Flow Could not be loaded

### ISSUE THREAD

**Issue by flixlix** [mitch-dc/volkswagen_we_connect_id#1]
## Version of the custom_component

0.0

## Installation method (hacs / manual)
hacs

## Installation method of hass (venv, docker, hassio,...)
hassos

## Configuration

```yaml

No configuration via YAML, all through the UI.

```

## Describe the bug

I installed the integration automatically via hacs.
After installation and restart, the integration appeared in the ui integrations in the "Devices and Services" Page.
When I clicked this integration, it loaded for a while and after that, I got an error.
![image](https://user-images.githubusercontent.com/61006057/149764991-e9dafef4-6cb0-4335-8da4-5661fc64fc8f.png)

## Debug log

```text

2022-01-17 11:48:58 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration volkswagen_we_connect_id: No module named 'ascii_magic'

```

**Comment by mitch-dc** [comment]
Fixed in latest version!

**Comment by flixlix** [comment]
Works now. Thank you very much!
