### ISSUE TITLE
Invalid config - The following integrations and platforms could not be set up:

### ISSUE THREAD

**Issue by flixlix** [mitch-dc/volkswagen_we_connect_id#10]
## Version of the custom_component

v0.0.7

## Installation method (hacs / manual)
hacs

## Installation method of hass (venv, docker, hassio,...)
HassOS

## Configuration

```yaml

No YAML configuration required

```

## Describe the bug

After updating Home Assistant to its latest version (2022.02.00) I get the following error:
![image](https://user-images.githubusercontent.com/61006057/152247575-4ee81981-a910-43be-95d9-d1d360d03e5b.png)

## Debug log

```text
2022-02-02 22:15:49 ERROR (MainThread) [homeassistant.setup] Setup failed for volkswagen_we_connect_id: Unable to import component: No module named 'ascii_magic'
```

**Comment by strutings** [comment]
Install Python-Magic will fix it

**Comment by mitch-dc** [comment]
Added it to the manifest again:
https://github.com/mitch-dc/volkswagen_we_connect_id/tree/v0.0.7.1
