### ISSUE TITLE
Latest version does not work 0.1.0.2

### ISSUE THREAD

**Issue by vantech14** [mitch-dc/volkswagen_we_connect_id#100]
Hi, 

Using HA with HACS. The latest version downloads and installs correctly however previously working sensors either become unavailable or go to an unknown state, whereas some of them work fine. 

I left this overnight thinking it was an API issue and no success. 

Reverted back to the previous version this morning, all sensors are back online again.

Thanks.

**Comment by peerkn** [comment]
Hello,
i have the same problem. In version 0.0.14 the car was always active. In version 0.0.13 everything works fine. I reverted to this version.

Thanks for your great work.

**Comment by pplucky** [comment]
> Hello, i have the same problem. In version 0.0.14 the car was always active. In version 0.0.13 everything works fine. I reverted to this version.
> 
> Thanks for your great work.

Since 0.0.14, this is happening with some binary sensors, already reported in #82 and now in #96.

**Comment by pplucky** [comment]
> Hi,
> 
> Using HA with HACS. The latest version downloads and installs correctly however previously working sensors either become unavailable or go to an unknown state, whereas some of them work fine.
> 
> I left this overnight thinking it was an API issue and no success.
> 
> Reverted back to the previous version this morning, all sensors are back online again.
> 
> Thanks.

Have you tried removing the integration after installing the new version, and re-adding it again?

I know that this last version had some breaking changes somehow outlined in the [version changelog](https://github.com/mitch-dc/volkswagen_we_connect_id/releases/tag/v0.1.0.2):
![image](https://user-images.githubusercontent.com/16407309/202663857-300c42ce-d160-4944-8c4e-505a908b3bcf.png)

**Comment by vantech14** [comment]
Same issue even when removing previous install. 

This is all that works: 

![image](https://user-images.githubusercontent.com/76781626/202684979-d9396ab6-e5a6-44d1-99a2-f0f95415de08.png)

And this is from the entities page: 

![image](https://user-images.githubusercontent.com/76781626/202685112-abe2afa9-5e1f-4c3d-a571-07a1a38e3c1b.jpeg)

![image](https://user-images.githubusercontent.com/76781626/202685175-29f807dd-dc5c-4d16-9433-7fc3d95b4def.png)

![image](https://user-images.githubusercontent.com/76781626/202685222-cd430acc-372d-4d5b-98d0-21346f3ed95b.png)

![image](https://user-images.githubusercontent.com/76781626/202685268-69a42715-bfe2-4214-b684-be31f2a8b0eb.png)

![image](https://user-images.githubusercontent.com/76781626/202685324-e250cad0-0680-40f4-b319-253dce5cd2ee.png)

**Comment by pplucky** [comment]
@vantech14 May I ask which version of id software you have installed in your vehicle?

All this information is ONLY being brought from VW for vehicles with version 3.0+.

**Comment by vantech14** [comment]
@pplucky I'm on version 2 still so that explains it! Thanks

**Comment by peerkn** [comment]
2.4

pplucky ***@***.***> schrieb am Fr., 18. Nov. 2022, 13:12:

**Comment by pplucky** [comment]
@vantech14 Can you maybe close the issue, as this is actually a non-issue.

**Comment by peerkn** [comment]
Most of the ID user have only softwarw-version 2.4. They are waiting for ota 3.0.

**Comment by pplucky** [comment]
> Most of the ID user have only softwarw-version 2.4. They are waiting for ota 3.0.

Yes, but the API does not return the software version, so I suppose no distinction can be made by the component: it works if supported by software/API, otherwise you'd better disable the entities in the integration or ignore them as being unavailable.

**Comment by mitch-dc** [comment]
I want to add some time in figuring out a way to make this a little more pretty, for now i pulled the last release because people had breaking stuff.

**Comment by mitch-dc** [comment]
Added try/catch in latest beta release,
