### ISSUE TITLE
Feature req: Setting Target SOC

### ISSUE THREAD

**Issue by BugBasher28** [mitch-dc/volkswagen_we_connect_id#11]
The target SOC is one of the settings I change most often. 

I'd like to be able to change this through HASS, instead of just reading the current setting. I have limited skills but browsed through WeConnect-python and from charging_settings.py it does look like this is possible. (Once again, I'm not skilled)

**Comment by mitch-dc** [comment]
Already possible with the service:

`service: volkswagen_we_connect_id.volkswagen_id_set_target_soc
data:
  vin: xxxx
  target_soc: 80`

**Comment by BugBasher28** [comment]
Thanks. At least I pointed out twice that I'm not so skilled.

**Comment by mitch-dc** [comment]
That's not a problem. Everybody needs to figure it out sometime! 

Good luck with your automation :)
