### ISSUE TITLE
Health inspection no longer being supplied? Change in API?

### ISSUE THREAD

**Issue by pplucky** [mitch-dc/volkswagen_we_connect_id#110]
## Version of the custom_component
Happening in both v0.1.0.3 and v0.0.13

## Installation method (hacs / manual)
hacs

## Installation method of hass (venv, docker, hassio,...)
docker

## Configuration
NA

## Describe the bug
Health Inspection sensor simply vanished from 2 different HA instances with different custom component versions v0.1.0.3 and v0.0.13 (hence also different versions of the underlying [library](https://github.com/tillsteinbach/WeConnect-python) - v0.50.1 and 0.47.1).

That seems to make me suspect that there might have been a change in the API, considering that the sensor became unavailable in both HA instances at the same time.

Running [weconnect-cli](https://github.com/tillsteinbach/WeConnect-cli) seems to still bring the information, not sure about format or placement in terms of "hierarchy", compared to before.

As [weconnect-cli](https://github.com/tillsteinbach/WeConnect-cli) is also based in the library and it seems to work, anything else that can be checked before reporting it in the [library](https://github.com/tillsteinbach/WeConnect-python)?

![image](https://user-images.githubusercontent.com/16407309/206117763-7a22de04-ea5a-48e1-843f-066cf1a378b0.png)

## Debug log
NA

**Comment by pplucky** [comment]
@tillsteinbach Are you aware of any issues with Health Inspection data from the API. @mitch-dc In a new installation of the custom component, sensor is not even generated automatically.

**Comment by mitch-dc** [comment]
I removed it because it stopped working. Do you need it?

**Comment by pplucky** [comment]
> I removed it because it stopped working. Do you need it?

Considering this is information that appears in the We Connect app and in theory is provided via API, I would say we should keep it, no?

**Comment by mitch-dc** [comment]
Hmm it's not available for my car:

```
Model:             ID.4
Device Platform:   WCAR
Nickname:          Komo
Brand Code:        V
Role:              PRIMARY_USER
Enrollment Status: COMPLETED
User Role Status:  ENABLED
Capabilities: 28 items
        [webApp] Status: MISSING_LICENSE disabling: None (expires 2052-11-12T23:59:59+00:00)
        [automation] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [batteryColdWarning] disabling: True (expires 2052-11-12T23:59:59+00:00)
        [batterySupport] disabling: None
        [charging] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [chargingProfiles] disabling: None (expires 2024-09-24T23:59:59+00:00)
        [chargingStations] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [climatisation] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [climatisationTimers] disabling: None (expires 2024-09-24T23:59:59+00:00)
        [dealerAppointment] Status: INITIALLY_DISABLED, DISABLED_BY_USER disabling: True (expires 2052-11-12T23:59:59+00:00)
        [destinations] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [fuelStatus] disabling: None (expires 2024-09-24T23:59:59+00:00)
        [ignition] disabling: None (expires 2024-09-24T23:59:59+00:00)
        [mapUpdate] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [measurements] disabling: None (expires 2052-11-12T23:59:59+00:00)
        [onlineSpeech] Status: MISSING_LICENSE disabling: True (expires 2024-09-24T23:59:59+00:00)
        [parkingBrake] disabling: None (expires 2052-11-12T23:59:59+00:00)
        [parkingInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [parkingPosition] disabling: True (expires 2052-11-12T23:59:59+00:00)
        [personalizationOnline] disabling: True (expires 2052-11-12T23:59:59+00:00)
        [poiSearch] Status: MISSING_LICENSE disabling: True
        [readiness] disabling: None
        [routing] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [state] disabling: True (expires 2052-11-12T23:59:59+00:00)
        [trafficInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
        [vehicleLights] disabling: None (expires 2052-11-12T23:59:59+00:00)
        [vehicleWakeUpTrigger] disabling: None (expires 2052-11-12T23:59:59+00:00)
        [webRadio] disabling: True (expires 2024-09-24T23:59:59+00:00)
Domains: 13 items
[access] Elements: 1 items
        [accessStatus] (last captured 2022-12-14T08:06:04+00:00)
                Overall Status: safe
                Door Lock Status: locked
                Doors: 6 items
                        bonnet: closed, unknown lock state
                        trunk: closed, locked
                        rearRight: closed, locked
                        rearLeft: closed, locked
                        frontRight: closed, locked
                        frontLeft: closed, locked
                Windows: 7 items
                        sunRoof: unsupported
                        roofCover: unsupported
                        sunRoofRear: unsupported
                        frontLeft: closed
                        frontRight: closed
                        rearLeft: closed
                        rearRight: closed
[automation] Elements: 2 items
        [climatisationTimer] (last captured 2022-12-14T08:05:06+00:00)
                Time in Car: 2022-12-14T09:05:07+01:00 (captured at 2022-12-14T08:05:06+00:00)
                Timers: 2 items
                        1: Enabled: False at 16:10 on mondays tuesdays wednesdays thursdays fridays saturdays sundays
                        2: Enabled: False at 16:15 on mondays tuesdays wednesdays thursdays fridays saturdays sundays
        [chargingProfiles] (last captured 2022-12-14T08:05:06+00:00)
                Time in Car: 2022-12-14T09:05:07+01:00 (captured at 2022-12-14T08:05:06+00:00)
                        Profiles: 0 items
[userCapabilities] Elements: 1 items
        [capabilitiesStatus]
                Capabilities: 28 items
                        [webApp] Status: MISSING_LICENSE disabling: None (expires 2052-11-12T23:59:59+00:00)
                        [automation] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [batteryColdWarning] disabling: True (expires 2052-11-12T23:59:59+00:00)
                        [batterySupport] disabling: None
                        [charging] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [chargingProfiles] disabling: None (expires 2024-09-24T23:59:59+00:00)
                        [chargingStations] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [climatisation] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [climatisationTimers] disabling: None (expires 2024-09-24T23:59:59+00:00)
                        [dealerAppointment] Status: INITIALLY_DISABLED, DISABLED_BY_USER disabling: True (expires 2052-11-12T23:59:59+00:00)
                        [destinations] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [fuelStatus] disabling: None (expires 2024-09-24T23:59:59+00:00)
                        [ignition] disabling: None (expires 2024-09-24T23:59:59+00:00)
                        [mapUpdate] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [measurements] disabling: None (expires 2052-11-12T23:59:59+00:00)
                        [onlineSpeech] Status: MISSING_LICENSE disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [parkingBrake] disabling: None (expires 2052-11-12T23:59:59+00:00)
                        [parkingInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [parkingPosition] disabling: True (expires 2052-11-12T23:59:59+00:00)
                        [personalizationOnline] disabling: True (expires 2052-11-12T23:59:59+00:00)
                        [poiSearch] Status: MISSING_LICENSE disabling: True
                        [readiness] disabling: None
                        [routing] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [state] disabling: True (expires 2052-11-12T23:59:59+00:00)
                        [trafficInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
                        [vehicleLights] disabling: None (expires 2052-11-12T23:59:59+00:00)
                        [vehicleWakeUpTrigger] disabling: None (expires 2052-11-12T23:59:59+00:00)
                        [webRadio] disabling: True (expires 2024-09-24T23:59:59+00:00)
[charging] Elements: 5 items
        [batteryStatus] (last captured 2022-12-14T09:55:51+00:00)
                Current SoC: 58%
                Range: 124km
        [chargingStatus] (last captured 2022-12-14T09:55:51+00:00)
                State: charging
                Mode: manual
                Remaining Charging Time: 350 minutes
                Charge Power: 7.0 kW
                Charge Rate: 17.0 km/h
                Charge Type: ac
                Charging Settings: default
        [chargingSettings] (last captured 2022-12-14T09:55:51+00:00)
                Request: settings operation, status successful  Request Id: 60530223-cbc6-4326-bd8b-f84f95625ad5
                Maximum Charge Current AC: reduced
                Auto Unlock When Charged: off
                Auto Unlock When Charged AC: off
                Target SoC: 100 %
        [chargeMode]
                Preferred charge mode: manual
                Available charge modes: [manual]
        [plugStatus] (last captured 2022-12-14T08:06:02+00:00)
                Plug: connected, locked, External Power: active, Led color: green
[chargingProfiles] Elements: 1 items
        [chargingProfilesStatus] (last captured 2022-12-14T08:05:06+00:00)
                Time in Car: 2022-12-14T09:05:07+01:00 (captured at 2022-12-14T08:05:06+00:00)
                        Profiles: 0 items
[climatisation] Elements: 3 items
        [climatisationStatus] (last captured 2022-12-14T08:05:23+00:00)
                State: off
                Remaining Climatization Time: 0 min
        [climatisationSettings] (last captured 2022-12-14T08:05:09+00:00)
                Target Temperature in °C: 21.0 °C
                Target Temperature in °F: 70.0 °F
                Temperature unit in car: celsius
                Start climatization after unlock: True
                Window heating: True
                Heating Front Left Seat: True
                Heating Front Right Seat: True
        [windowHeatingStatus] (last captured 2022-12-14T08:05:10+00:00)
                Windows: 2 items
                        front: off
                        rear: off
[fuelStatus] Elements: 1 items
        [rangeStatus] (last captured 2022-12-14T09:55:51+00:00)
                Car Type: electric
                Total Range: 124 km
                Primary Engine: electric  SoC: 58% (124 km)
[vehicleLights] Elements: 1 items
        [lightsStatus] (last captured 2022-12-14T08:05:09+00:00)
                Lights: 2 items
                        right: off
                        left: off
[lvBattery] Elements: 1 items
        [lvBatteryStatus]
                Battery Support: enabled
[readiness] Elements: 1 items
        [readinessStatus]
                Connection State:
                        Is online: True
                        Battery power level: comfort
                        Daily Power Budget Available: True
                Connection Warning:
                        Insufficient Battery Level Warning: False
                        Daily Power Budget Warning: False
[measurements] Elements: 2 items
        [rangeStatus] (last captured 2022-12-14T09:55:40+00:00)
                Electric Range: 124km
        [odometerStatus] (last captured 2022-12-14T08:03:51+00:00)
                Odometer: 46880km
[batterySupport] Elements: 1 items
        [batterySupportStatus]
                Battery Support: enabled
[parking] Elements: 1 items
        [parkingPosition] (last captured 2022-12-14T08:05:06+00:00)
                Latitude: 51
                Longitude: 5
```

**Comment by pplucky** [comment]
> Hmm it's not available for my car:
> 
> ```
> Model:             ID.4
> Device Platform:   WCAR
> Nickname:          Komo
> Brand Code:        V
> Role:              PRIMARY_USER
> Enrollment Status: COMPLETED
> User Role Status:  ENABLED
> Capabilities: 28 items
>         [webApp] Status: MISSING_LICENSE disabling: None (expires 2052-11-12T23:59:59+00:00)
>         [automation] disabling: True (expires 2024-09-24T23:59:59+00:00)
>         [batteryColdWarning] disabling: True (expires 2052-11-12T23:59:59+00:00)
>         [batterySupport] disabling: None
>         [charging] disabling: True (expires 2024-09-24T23:59:59+00:00)
>         [chargingProfiles] disabling: None (expires 2024-09-24T23:59:59+00:00)
>         [chargingStations] disabling: True (expires 2024-09-24T23:59:59+00:00)
>         [climatisation] disabling: True (expires 2024-09-24T23:59:59+00:00)
>         [climatisationTimers] disabling: None (expires 2024-09-24T23:59:59+00:00)
>         [dealerAppointment] Status: INITIALLY_DISABLED, DISABLED_BY_USER disabling: True (expires 2052-11-12T23:59:59+00:00)
>         [destinations] disabling: True (expires 2024-09-24T23:59:59+00:00)
>         [fuelStatus] disabling: None (expires 2024-09-24T23:59:59+00:00)
>         [ignition] disabling: None (expires 2024-09-24T23:59:59+00:00)
>         [mapUpdate] disabling: True (expires 2024-09-24T23:59:59+00:00)
>         [measurements] disabling: None (expires 2052-11-12T23:59:59+00:00)
>         [onlineSpeech] Status: MISSING_LICENSE disabling: True (expires 2024-09-24T23:59:59+00:00)
>         [parkingBrake] disabling: None (expires 2052-11-12T23:59:59+00:00)
>         [parkingInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
>         [parkingPosition] disabling: True (expires 2052-11-12T23:59:59+00:00)
>         [personalizationOnline] disabling: True (expires 2052-11-12T23:59:59+00:00)
>         [poiSearch] Status: MISSING_LICENSE disabling: True
>         [readiness] disabling: None
>         [routing] disabling: True (expires 2024-09-24T23:59:59+00:00)
>         [state] disabling: True (expires 2052-11-12T23:59:59+00:00)
>         [trafficInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
>         [vehicleLights] disabling: None (expires 2052-11-12T23:59:59+00:00)
>         [vehicleWakeUpTrigger] disabling: None (expires 2052-11-12T23:59:59+00:00)
>         [webRadio] disabling: True (expires 2024-09-24T23:59:59+00:00)
> Domains: 13 items
> [access] Elements: 1 items
>         [accessStatus] (last captured 2022-12-14T08:06:04+00:00)
>                 Overall Status: safe
>                 Door Lock Status: locked
>                 Doors: 6 items
>                         bonnet: closed, unknown lock state
>                         trunk: closed, locked
>                         rearRight: closed, locked
>                         rearLeft: closed, locked
>                         frontRight: closed, locked
>                         frontLeft: closed, locked
>                 Windows: 7 items
>                         sunRoof: unsupported
>                         roofCover: unsupported
>                         sunRoofRear: unsupported
>                         frontLeft: closed
>                         frontRight: closed
>                         rearLeft: closed
>                         rearRight: closed
> [automation] Elements: 2 items
>         [climatisationTimer] (last captured 2022-12-14T08:05:06+00:00)
>                 Time in Car: 2022-12-14T09:05:07+01:00 (captured at 2022-12-14T08:05:06+00:00)
>                 Timers: 2 items
>                         1: Enabled: False at 16:10 on mondays tuesdays wednesdays thursdays fridays saturdays sundays
>                         2: Enabled: False at 16:15 on mondays tuesdays wednesdays thursdays fridays saturdays sundays
>         [chargingProfiles] (last captured 2022-12-14T08:05:06+00:00)
>                 Time in Car: 2022-12-14T09:05:07+01:00 (captured at 2022-12-14T08:05:06+00:00)
>                         Profiles: 0 items
> [userCapabilities] Elements: 1 items
>         [capabilitiesStatus]
>                 Capabilities: 28 items
>                         [webApp] Status: MISSING_LICENSE disabling: None (expires 2052-11-12T23:59:59+00:00)
>                         [automation] disabling: True (expires 2024-09-24T23:59:59+00:00)
>                         [batteryColdWarning] disabling: True (expires 2052-11-12T23:59:59+00:00)
>                         [batterySupport] disabling: None
>                         [charging] disabling: True (expires 2024-09-24T23:59:59+00:00)
>                         [chargingProfiles] disabling: None (expires 2024-09-24T23:59:59+00:00)
>                         [chargingStations] disabling: True (expires 2024-09-24T23:59:59+00:00)
>                         [climatisation] disabling: True (expires 2024-09-24T23:59:59+00:00)
>                         [climatisationTimers] disabling: None (expires 2024-09-24T23:59:59+00:00)
>                         [dealerAppointment] Status: INITIALLY_DISABLED, DISABLED_BY_USER disabling: True (expires 2052-11-12T23:59:59+00:00)
>                         [destinations] disabling: True (expires 2024-09-24T23:59:59+00:00)
>                         [fuelStatus] disabling: None (expires 2024-09-24T23:59:59+00:00)
>                         [ignition] disabling: None (expires 2024-09-24T23:59:59+00:00)
>                         [mapUpdate] disabling: True (expires 2024-09-24T23:59:59+00:00)
>                         [measurements] disabling: None (expires 2052-11-12T23:59:59+00:00)
>                         [onlineSpeech] Status: MISSING_LICENSE disabling: True (expires 2024-09-24T23:59:59+00:00)
>                         [parkingBrake] disabling: None (expires 2052-11-12T23:59:59+00:00)
>                         [parkingInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
>                         [parkingPosition] disabling: True (expires 2052-11-12T23:59:59+00:00)
>                         [personalizationOnline] disabling: True (expires 2052-11-12T23:59:59+00:00)
>                         [poiSearch] Status: MISSING_LICENSE disabling: True
>                         [readiness] disabling: None
>                         [routing] disabling: True (expires 2024-09-24T23:59:59+00:00)
>                         [state] disabling: True (expires 2052-11-12T23:59:59+00:00)
>                         [trafficInformation] disabling: True (expires 2024-09-24T23:59:59+00:00)
>                         [vehicleLights] disabling: None (expires 2052-11-12T23:59:59+00:00)
>                         [vehicleWakeUpTrigger] disabling: None (expires 2052-11-12T23:59:59+00:00)
>                         [webRadio] disabling: True (expires 2024-09-24T23:59:59+00:00)
> [charging] Elements: 5 items
>         [batteryStatus] (last captured 2022-12-14T09:55:51+00:00)
>                 Current SoC: 58%
>                 Range: 124km
>         [chargingStatus] (last captured 2022-12-14T09:55:51+00:00)
>                 State: charging
>                 Mode: manual
>                 Remaining Charging Time: 350 minutes
>                 Charge Power: 7.0 kW
>                 Charge Rate: 17.0 km/h
>                 Charge Type: ac
>                 Charging Settings: default
>         [chargingSettings] (last captured 2022-12-14T09:55:51+00:00)
>                 Request: settings operation, status successful  Request Id: 60530223-cbc6-4326-bd8b-f84f95625ad5
>                 Maximum Charge Current AC: reduced
>                 Auto Unlock When Charged: off
>                 Auto Unlock When Charged AC: off
>                 Target SoC: 100 %
>         [chargeMode]
>                 Preferred charge mode: manual
>                 Available charge modes: [manual]
>         [plugStatus] (last captured 2022-12-14T08:06:02+00:00)
>                 Plug: connected, locked, External Power: active, Led color: green
> [chargingProfiles] Elements: 1 items
>         [chargingProfilesStatus] (last captured 2022-12-14T08:05:06+00:00)
>                 Time in Car: 2022-12-14T09:05:07+01:00 (captured at 2022-12-14T08:05:06+00:00)
>                         Profiles: 0 items
> [climatisation] Elements: 3 items
>         [climatisationStatus] (last captured 2022-12-14T08:05:23+00:00)
>                 State: off
>                 Remaining Climatization Time: 0 min
>         [climatisationSettings] (last captured 2022-12-14T08:05:09+00:00)
>                 Target Temperature in °C: 21.0 °C
>                 Target Temperature in °F: 70.0 °F
>                 Temperature unit in car: celsius
>                 Start climatization after unlock: True
>                 Window heating: True
>                 Heating Front Left Seat: True
>                 Heating Front Right Seat: True
>         [windowHeatingStatus] (last captured 2022-12-14T08:05:10+00:00)
>                 Windows: 2 items
>                         front: off
>                         rear: off
> [fuelStatus] Elements: 1 items
>         [rangeStatus] (last captured 2022-12-14T09:55:51+00:00)
>                 Car Type: electric
>                 Total Range: 124 km
>                 Primary Engine: electric  SoC: 58% (124 km)
> [vehicleLights] Elements: 1 items
>         [lightsStatus] (last captured 2022-12-14T08:05:09+00:00)
>                 Lights: 2 items
>                         right: off
>                         left: off
> [lvBattery] Elements: 1 items
>         [lvBatteryStatus]
>                 Battery Support: enabled
> [readiness] Elements: 1 items
>         [readinessStatus]
>                 Connection State:
>                         Is online: True
>                         Battery power level: comfort
>                         Daily Power Budget Available: True
>                 Connection Warning:
>                         Insufficient Battery Level Warning: False
>                         Daily Power Budget Warning: False
> [measurements] Elements: 2 items
>         [rangeStatus] (last captured 2022-12-14T09:55:40+00:00)
>                 Electric Range: 124km
>         [odometerStatus] (last captured 2022-12-14T08:03:51+00:00)
>                 Odometer: 46880km
> [batterySupport] Elements: 1 items
>         [batterySupportStatus]
>                 Battery Support: enabled
> [parking] Elements: 1 items
>         [parkingPosition] (last captured 2022-12-14T08:05:06+00:00)
>                 Latitude: 51
>                 Longitude: 5
> ```

From [weconnect-cli](https://github.com/tillsteinbach/WeConnect-cli), from a friend's id4 (appeared right below readiness):
![image](https://user-images.githubusercontent.com/16407309/207576567-42c69206-e287-43f6-b022-9ea2a59ef5ed.png)

It may be something with the setup of your vehicle, so I think we should definitely this back to the custom component.

**Comment by mitch-dc** [comment]
On what software is that car?
Mine is on 3.0.

**Comment by mitch-dc** [comment]
If it's different between the software versions we need to check all the values

**Comment by pplucky** [comment]
> On what software is that car? Mine is on 3.0.

3.1.0
