### ISSUE TITLE
Add Start/Stop charging functionality

### ISSUE THREAD

**Issue by Matt2k34** [mitch-dc/volkswagen_we_connect_id#112]
**Is your feature request related to a problem? Please describe.**
When using the app, you can swipe left/right on the "start charging" bar which will start the car charging if it has power available.

**Describe the solution you'd like**
The ability to toggle this on/off from home assistant.

**Describe alternatives you've considered**
Using a smart plug works - but the car doesn't seemingly like losing power when charging on a 3pin.

The "home location" charging settings are ropey at best. Half the time at home my charging location data is empty - so the car doesn't follow the rules and I can't add/remove/update them,

**Additional context**
Getting an electrician is proving difficult currently, because they're all busy installing solar/batteries/regular winter peak trading. I'm still using a "granny charger" which is more than adequate for my needs in terms of charge speed - but it'd be good if I could schedule the start/stop "nicely" rather than cutting the power to the car.

**Comment by mitch-dc** [comment]
This is already possible. 
Take look at the available services! :) The car wil always start charging when you plug it in but you can then stop and start all you want.

**Comment by Matt2k34** [comment]
Sorry - you're absolutely correct. I was expecting a bool type-option under the Device. Hadn't thought to check in services :)

for my benefit - is there an easy way to see what's available via the integration? If I click on the ~57 entities available, it only gives me the sensors / bools but doesn't list any services. Appreciate that's more of a HA question but I'm not sure how you'd know by looking at the integration it was available.

**Comment by mitch-dc** [comment]
Developer Tools - Services - Start typing  Volkswagen. 


This works with all integrations!!

Good luck on your automation :)

**Comment by Matt2k34** [comment]
Thank you so much :)
