### ISSUE TITLE
no update of Sensors without restart the configuration

### ISSUE THREAD

**Issue by Schnabel80** [mitch-dc/volkswagen_we_connect_id#123]
Hey, thank you for the integration. unfortunly i have a problem, After starting the integration i get the actual values (SOC). But they don't get a update, i have du reload the integration for new values.

thanks a lot.

**Comment by mitch-dc** [comment]
Hmm, my info is updated every 30 seconds.

**Comment by northalpha** [comment]
Can confirm that at least SoC Status is not updated. This was working to the best of my knowledge sometime ago. I have to say that the start of the integration is taking ages (sometimes 3-5 minutes, HA is complaining in the logs as well) not sure if related.

**Comment by siggmur** [comment]
I got the same issue, need to restart the integration for updates to work

**Comment by bedaes** [comment]
May be related to https://github.com/mitch-dc/volkswagen_we_connect_id/issues/36 ?
