### ISSUE TITLE
ID Buzz Support

### ISSUE THREAD

**Issue by viddi87** [mitch-dc/volkswagen_we_connect_id#126]
ID Buzz is not showing any sensors and this error is showing in the logs.

An unsupported brandCode: N was provided, known values are [V, unknown brand code] please report this as a bug

**Comment by mitch-dc** [comment]
This will be fixed in the next version! :)

**Comment by viddi87** [comment]
> This will be fixed in the next version! :)
> 
> [tillsteinbach/WeConnect-python#94](https://github.com/tillsteinbach/WeConnect-python/issues/94)

Looks like it has already been fixed and released [weconnect 0.51.0](https://github.com/tillsteinbach/WeConnect-python/releases/tag/v0.51.0)

**Comment by mitch-dc** [comment]
https://github.com/mitch-dc/volkswagen_we_connect_id/releases/tag/v0.1.2

**Comment by viddi87** [comment]
the error went away but there are no sensors showing up, and nothing in the logs.

**Comment by Scheingeist** [comment]
Thanks for your nice Work, but i went in the same Issue with our Buzz. The Login is working but no Sensors or Controls shows up.

**Comment by viddi87** [comment]
I fixed that issue here 
[https://github.com/mitch-dc/volkswagen_we_connect_id/pull/139](url)
