### ISSUE TITLE
Start/stop charging buttons andset charging speed.

### ISSUE THREAD

**Issue by roppenheimer** [mitch-dc/volkswagen_we_connect_id#136]
Enhancement:

COuld we have a control to start/stop charging and also to set the AC charging speed - or am I missing something?

**Comment by mitch-dc** [comment]
These options are already available! :) see the integration page in Homeassistant.

**Comment by roppenheimer** [comment]
There is an option to toggle the charging speed, but I can’t see a way to set it to one or the other.
