### ISSUE TITLE
Unsupported charging status value

### ISSUE THREAD

**Issue by madd0** [mitch-dc/volkswagen_we_connect_id#141]
## Version of the custom_component
0.1.3

## Installation method (hacs / manual)
HACS

## Installation method of hass (venv, docker, hassio,...)
Hassio

## Configuration

```yaml

```

## Describe the bug

The following message started popping up in my logs. Reporting as requested.

## Debug log

```text

/vehicles/<VIN>/domains/charging/chargingStatus/request/<GUID>/status: An unsupported status: fail_plug_disconnected was provided, known values are [successful, fail, polling_timeout, in_progress, queued, delayed, timeout, fail_vehicle_is_offline, fail_ignition_on, fail_battery_low, fail_plug_error, fail_charge_plug_not_connected, fail_no_external_power, unknown status] please report this as a bug

```

**Comment by madd0** [comment]
Hmm... Looking at the code here I realized the error came from the WeConnect-python library, so actually created a [PR over there](https://github.com/tillsteinbach/WeConnect-python/pull/103).

If there is nothing to update here, this issue can be closed.

**Comment by mitch-dc** [comment]
Thanks! I will update version asap.
