### ISSUE TITLE
 I can’t get the "Volkswagen We Connect ID" to show up when I try to add the Integration?

### ISSUE THREAD

**Issue by gkrallo** [mitch-dc/volkswagen_we_connect_id#15]
Hi 
any idea of why I can’t get the "Volkswagen We Connect ID" to show up when I try to add the Integration?
I have used HACS to install and the files seems to be in the expected place

<img width="232" alt="image" src="https://user-images.githubusercontent.com/96731141/154078855-d6f6987b-5015-4a6e-bcd1-4dd030f206c3.png">

<img width="408" alt="image" src="https://user-images.githubusercontent.com/96731141/154079105-5315ac01-df4e-41c9-901a-af7fab827da1.png">

**Comment by jonasbkarlsson** [comment]
I had the same problem. Search with "volk" instead. Strange that "id" doesn't work...

**Comment by gkrallo** [comment]
Aha 
Thank you! 
I found it. 
I thought that i Manually went trough the list but obviously was that search method not better....
