### ISSUE TITLE
Not appearing in HACS and when manually installing, gets 500 error

### ISSUE THREAD

**Issue by nigels0** [mitch-dc/volkswagen_we_connect_id#153]
## Version of the custom_component

Latest

## Installation method (hacs / manual)

Missing in HACS, so used Manual method

## Installation method of hass (venv, docker, hassio,...)

Hassio on Raspberry

## Configuration

```yaml

Add your configuration here.

```

## Describe the bug

HACS no longer shows the Volkswagen ID integration, so I installed it manually. On trying to add the integration, I get a 500 server error

## Debug log

```text

Add your logs here.

```

**Comment by flixlix** [comment]
As described in the README:
> ... add this repository as a custom repository.

Go into HACS -> Integrations -> Vertical three dot Overflow Menu -> Custom Repositories -> Write the following URL: https://github.com/mitch-dc/volkswagen_we_connect_id -> In Categroy, select: Integrations -> Now it should be visible as a new repository.

Note:
Currently, this integration is unfortunately not working, please check: #152

**Comment by nigels0** [comment]
It's not in the current READMR.

**Comment by flixlix** [comment]
I can't help you on the manual install, but it's definitely in the current README.
![Screenshot of the README at 17:41 02/03/2023](https://user-images.githubusercontent.com/61006057/222508579-f04b05c5-73db-4980-bd2b-79e741dd89fb.png)

**Comment by flixlix** [comment]
But also, as I said, this integration is currently broken, I don't know if your error has anything to do with that. Without further configuration and updating dependencies, you currently can't use this integration
