### ISSUE TITLE
Error by add Integration 

### ISSUE THREAD

**Issue by Schnabel80** [mitch-dc/volkswagen_we_connect_id#157]
## Version of the custom_component

V0.1.5

## Installation method (hacs / manual)
Hacs 

## Installation method of hass (venv, docker, hassio,...)

Hassio 

## Configuration

```yaml

Add your configuration here.

```

## Describe the bug

HA Write the following Error

Logger: homeassistant.config_entries
Source: config_entries.py:1376 
First occurred: 09:57:45 (1 occurrences) 
Last logged: 09:57:45

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 81, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1376, in async_forward_entry_setups
    await asyncio.gather(
asyncio.exceptions.CancelledError

## Debug log

```text

Add your logs here.

```

**Comment by dellock6** [comment]
I had the same issue with the latest versions, And I couldn't understand why it stopped working after it was all ok for a few months. Today I updated HA to 2023.03.1 and we_connect_id to 0.1.5 and I still had the same initialization error, but then I looked at the log and saw this at the last lines:

File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 242, in doWebAuth
    raise AuthentificationError('You have to login at myvolkswagen.de and accept the terms and conditions')
weconnect.errors.AuthentificationError: You have to login at myvolkswagen.de and accept the terms and conditions

So, I went to myvolkswagen.de and logged in, accepted the different authorization requests, and when I reloaded the integration in HA it started working again. Hope it helps.

**Comment by Schnabel80** [comment]
perfect now it works
