### ISSUE TITLE
Cannot configure integration - weconnect.errors.APICompatibilityError: No user id provided

### ISSUE THREAD

**Issue by gapthorpe** [mitch-dc/volkswagen_we_connect_id#158]
Upgraded to 2023.3.1, has stopped the dependency issue but unable to configure the integration:

- Configuration of user / password in Add Integration gives "Unexpected error" 
- In logs:
```
Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input
    await hass.async_add_executor_job(we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 184, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 243, in doWebAuth
    raise APICompatibilityError('No user id provided')
weconnect.errors.APICompatibilityError: No user id provided
```

Have definitely set the username in the screen, so not sure why failing?

**Comment by PalmSwe** [comment]
Have you updated to the latest version? 0.1.5.
That did the trick for me.

**Comment by gapthorpe** [comment]
Unfortunately not - tried a complete restart of the containers as well but still seeing the same error

**Comment by Maxi531** [comment]
Same issue for me here, my error looks like this
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 81, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1376, in async_forward_entry_setups
    await asyncio.gather(
asyncio.exceptions.CancelledError`

Version is 0.1.5 and HA Core 2023.3.1

**Comment by gapthorpe** [comment]
Ah unfortunately mine refuses to created it...

**Comment by robinostlund** [comment]
Could also be issues with weconnect, that has happened before 😄 it is working for me and i am running in docker container.

**Comment by IHateNameStealers** [comment]
Installed it on a clean system (using hacs).
All working straight out of the box!

**Comment by gapthorpe** [comment]
It’s strange, was all working before but now getting this error. Have tried deleting and removing the custom integration but still getting the same

**Comment by gapthorpe** [comment]
Solved! The We Connect app didn’t show anything, but going on to the Volkswagen.co.uk site it then asked about consent for marketing - clicking ‘Not Now’ seems to have got past this! Thanks!

**Comment by Lluis-zrc** [comment]
Same problem here. 
Logger: custom_components.volkswagen_we_connect_id.config_flow
Source: custom_components/volkswagen_we_connect_id/config_flow.py:39 
Integration: Volkswagen We Connect ID 
First occurred: 17:09:10 (1 occurrences) 
Last logged: 17:09:10

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input
    await hass.async_add_executor_job(we_connect.login)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 184, in login
    self.__session.login()
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login
    response = self.doWebAuth(authorizationUrl)
  File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 242, in doWebAuth
    raise AuthentificationError('You have to login at myvolkswagen.de and accept the terms and conditions')
weconnect.errors.AuthentificationError: You have to login at myvolkswagen.de and accept the terms and conditions

**Comment by Lluis-zrc** [comment]
> Solved! The We Connect app didn’t show anything, but going on to the Volkswagen.co.uk site it then asked about consent for marketing - clicking ‘Not Now’ seems to have got past this! Thanks!

I logged in volkswagen.de and omited publicity config. I already did this in volkswagen.es but it seems it didn’t work.

**Comment by maartenweyn** [comment]
> Same problem here.
> 
> Home Assistant 2023.3.1 Supervisor 2023.01.1 Operating System 9.5
> 
> HACS Ver. 1.31.0
> 
> vlokswagen ID integration v.0.1.5
> 
> Logger: custom_components.volkswagen_we_connect_id.config_flow Source: custom_components/volkswagen_we_connect_id/config_flow.py:39 Integration: Volkswagen We Connect ID First occurred: 17:09:10 (1 occurrences) Last logged: 17:09:10
> 
> Unexpected exception Traceback (most recent call last): File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 64, in async_step_user info = await validate_input(self.hass, user_input) File "/config/custom_components/volkswagen_we_connect_id/config_flow.py", line 39, in validate_input await hass.async_add_executor_job(we_connect.login) File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 184, in login self.__session.login() File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 76, in login response = self.doWebAuth(authorizationUrl) File "/usr/local/lib/python3.10/site-packages/weconnect/auth/we_connect_session.py", line 242, in doWebAuth raise AuthentificationError('You have to login at myvolkswagen.de and accept the terms and conditions') weconnect.errors.AuthentificationError: You have to login at myvolkswagen.de and accept the terms and conditions

go to https://www.volkswagen.de/ and login there, accept the concent over there and it works afterwards
