### ISSUE TITLE
Issue after last update

### ISSUE THREAD

**Issue by radeon79** [mitch-dc/volkswagen_we_connect_id#16]
I have more errors logs after last update. Do you check please?

Logger: weconnect
Source: /usr/local/lib/python3.9/site-packages/weconnect/elements/generic_status.py:81
First occurred: 16 febbraio 2022, 20:47:51 (4842 occurrences)
Last logged: 08:34:23

/vehicles/My_vin/domains/charging/chargingStatus: Unknown attribute chargeType with value invalid
/vehicles/My_vin/domains/charging/chargingStatus: Unknown attribute chargingSettings with value default
/vehicles/My_vin/domains/charging/chargingStatus: Unknown attribute chargeType with value ac
/vehicles/My_vin/domains/charging/chargingStatus: Unknown attribute chargingSettings with value profile

**Comment by mitch-dc** [comment]
I'm aware of that, it's an issue in the library i use and they are working on it :)
