### ISSUE TITLE
volkswagen_we_connect_id not found by HACS

### ISSUE THREAD

**Issue by BKneer** [mitch-dc/volkswagen_we_connect_id#167]
## Version of the custom_component
 manifest shows 1.0

## Installation method (hacs / manual)
manual

## Installation method of hass (venv, docker, hassio,...)
Hassio

## Configuration
not possible because not found by HACS
```yaml

Add your configuration here.

```

## Describe the bug

See above

## Debug log

```text

Add your logs here.

```

**Comment by pplucky** [comment]
Have you tried [adding the custom repository](https://github.com/mitch-dc/volkswagen_we_connect_id#hacs) `mitch-dc/volkswagen_we_connect_id` in HACS and restart HA in case it doesn't appear immediately?

**Comment by BKneer** [comment]
Hi, thanks for the help. Searching for the whole path worked and I could find the repo. 
The next question is how to configure it. I modified the FIN (this is what I found for my car - I guess in your systems.yaml it's called VIM, right?). After a reboot I still don't see the entities.

**Comment by pplucky** [comment]
You just need to [add the integration in Home Assistant](https://my.home-assistant.io/redirect/config_flow_start?domain=volkswagen_we_connect_id) and enter the username and password you use to connect to WeConnectID app.

And be patient, because VW servers are not the fastest or more reliable...

**Comment by BKneer** [comment]
didn't help... the only thing I see if I select the volkswagen_we_connect_id card in HACS is the info.md content.
I've removed the volkswagen_we_connect_id folder and cloned again the git repo. (had to copy the volkswagen_we_connect_id folder from the repo to the custom_integration folder directly).
Then I've tried to call python in the ssh shell and noticed that python might not be installed at all... Could this be possible. I'm using home assistant on a Raspi home assistant docker. I would guess that Python should be installed by default. 
Any idea?

**Comment by BKneer** [comment]
seems something is wrong in my system. I've installed the package again and rebooted. Seems reboot and everything went fine but still I only see the info.md if I select the volkswagen_we_connect_id integration icon. There is no option to enter my credential. I guess I need to give up.

**Comment by pplucky** [comment]
You know that adding an integration is NOT done in HACS, but done in HA settings, Devices & Services, Add integration button and the searching for Volkswagen and only after that, enter username and password?

**Comment by BKneer** [comment]
shit... that was my fault... I didn't check this again after I couldn't find the integration the firsts time. After re-installation I've found it and could connect to my ID3. Thanks a lot for your great support and sorry for the troubles!!!

**Comment by Josefen** [comment]
> Hi, thanks for the help. Searching for the whole path worked and I could find the repo.

I can't find it via HACS 30th of april.
