### ISSUE TITLE
Integration stopped working (setup ... is taking over 10 seconds)

### ISSUE THREAD

**Issue by soeffi** [mitch-dc/volkswagen_we_connect_id#173]
## Version of the custom_component

v0.1.5

## Installation method (hacs / manual)
hacs

## Installation method of hass (venv, docker, hassio,...)
docker (2023.3.3)

## Configuration
via UI

## Describe the bug
Integration stopped working 2-3 weeks ago. I updated ha and integration to latest version. Did a login to myvolkswagen and accepted new terms and conditions.

Still, the Integration is not working, after removing the integration and reinstall via hacs, it takes quite some time then reports "success", but does not show any entities or devices.

## Debug log

Can't find helpful logs, even at level info. The only relevant output I could find:

```text

WARNING (MainThread) [homeassistant.components.number] Setup of number platform volkswagen_we_connect_id is taking over 10 seconds.

```

**Comment by flixlix** [comment]
Have you tried this? 
https://github.com/mitch-dc/volkswagen_we_connect_id/issues/162#issuecomment-1455190376

**Comment by soeffi** [comment]
> Have you tried this?

I did, and it didn't help.

But I got it solved anyhow:

I registered the account with a Gmail address. Interestingly, the app and website do not care whether I use ...@gmail.com or ...@googlemail.com. With the integration it obviously matters... with the right domain it now works flawlessly again...
