### ISSUE TITLE
Integration broke on after update to HA 2023.4.4

### ISSUE THREAD

**Issue by Rawet** [mitch-dc/volkswagen_we_connect_id#176]
## Describe the bug

Integration does not start in latest Home Assistant
Was ofcourse working before update.

## Log

```text

Logger: homeassistant.config_entries
Source: custom_components/volkswagen_we_connect_id/__init__.py:48
Integration: Volkswagen We Connect ID
First occurred: 20:14:15 (1 occurrences)
Last logged: 20:14:15

Error setting up entry Volkswagen We Connect ID for volkswagen_we_connect_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/volkswagen_we_connect_id/__init__.py", line 48, in async_setup_entry
    await hass.async_add_executor_job(_we_connect.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 193, in update
    self.updateVehicles(updateCapabilities=updateCapabilities, updatePictures=updatePictures, force=force, selective=selective)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 202, in updateVehicles
    data = self.fetchData(url, force)
  File "/usr/local/lib/python3.10/site-packages/weconnect/weconnect.py", line 388, in fetchData
    raise RetrievalError(f'Could not fetch data. Status Code was: {statusResponse.status_code}')
weconnect.errors.RetrievalError: Could not fetch data. Status Code was: 503


```

**Comment by PalmSwe** [comment]
Same problem here. VW integration not working on two diffrent versions of HA that I have. I have HA version 2023.3.6 and 2023.4.4.
Other integration to VW as for example the Tronity-app, is still working for me and correctly connected to the car.

**Comment by Rawet** [comment]
> Same here - could be a VW thing though too as the app hiccuped earlier - however the other VWID integration with HA is still working as is Tronity.

True, the app is dead..
I just thought updating HA might broke it but its 100% Volkswagens service thats down, my car was updated 6h ago and it doesnt seem to want to update

**Comment by Rawet** [comment]
> Same problem here. VW integration not working on two diffrent versions of HA that I have. I have HA version 2023.3.6 and 2023.4.4. Other integration to VW as for example the Tronity-app, is still working for me and correctly connected to the car.

Funny, but could it be old data? i never used Tronity (but i looked it up and it look promising, thanks!) but im guessing its fetching data and stores it on their database

**Comment by roppenheimer** [comment]
Same here. Not sure if it's the upgrage or the VW servers

**Comment by Rawet** [comment]
> Same here. Not sure if it's the upgrage or the VW servers

I would guess VW fault, because the WE Connect ID app does not work currently

**Comment by wgumaa** [comment]
Same issue here

**Comment by Grogilein** [comment]
I use this integration and additionally EVCC on another server.. Currently, the VW server is apparently broken, because I also get this message in EVCC:   cannot get vehicles: unexpected status: 503 (Service Unavailable) / .Soc:     vehicle not available: cannot create vehicle 'id': cannot get vehicles: unexpected status: 503 (Service Unavailable)

This is not the first time Volkswagen has had problems with their funny servers.

**Comment by PalmSwe** [comment]
> > Same problem here. VW integration not working on two diffrent versions of HA that I have. I have HA version 2023.3.6 and 2023.4.4. Other integration to VW as for example the Tronity-app, is still working for me and correctly connected to the car.
> 
> Funny, but could it be old data? i never used Tronity (but i looked it up and it look promising, thanks!) but im guessing its fetching data and stores it on their database

Its still fresh data. I still get notice in Tronity when my car gets charged or when I'm done with a trip. For me its only this integration on HA that is not working correctly / don't have contact with the car.

**Comment by dellock6** [comment]
> > Same problem here. VW integration not working on two diffrent versions of HA that I have. I have HA version 2023.3.6 and 2023.4.4. Other integration to VW as for example the Tronity-app, is still working for me and correctly connected to the car.
> 
> Funny, but could it be old data? i never used Tronity (but i looked it up and it look promising, thanks!) but im guessing its fetching data and stores it on their database

no, tronity keeps showing updated data, I just monitored these days all the charging sessions, while the this app is offline for me since a week already. As much as VW servers are not really reliable, this time it doesn't seem to be their fault.

**Comment by andre68723** [comment]
using [IDDataLogger](https://github.com/robske110/IDDataLogger) and [VWsFriend](https://github.com/tillsteinbach/VWsFriend) in parallel.

IDDataLogger is still working.
VWsFriend last update 12.04.2023, since then no updates. I think this uses they same python lib as here - 
https://pypi.org/project/weconnect/ 

So rather open a issue there ? https://github.com/tillsteinbach/WeConnect-python/issues

**Comment by wgumaa** [comment]
I re-installed the integration 5 minutes ago and signed in. It seems to be working and my entities are reporting. 

I had disabled it and unintsalled it when the first error occured thinking it was a glitch. When I resintalled it yesterday didn't allow me to always giving an error when entering my credentials. 

I would suggest others try and it works then the issue can be closed.

**Comment by dellock6** [comment]
It worked for me too now. After a few "unexpected error" attempts, I opened the weconnect id website on the same browser where I had HA open too, logged into it, and then also HA integration was able to connect and list all entities and their status.

**Comment by wgumaa** [comment]
> It worked for me too now. After a few "unexpected error" attempts, I opened the weconnect id website on the same browser where I had HA open too, logged into it, and then also HA integration was able to connect and list all entities and their status.

All entities? My tracker either reports "Home" or "Away" now it's reporting "Unkown". Maybe because my  wife is using the car in her profile?

**Comment by dellock6** [comment]
I have 61 entities, not sure if they are all. Also, I'm still on 2.4 id software, so some entities like door/window/trunk status are unknown.

**Comment by andre68723** [comment]
deactivated and activated again 1min later. started working again

**Comment by Rawet** [comment]
Marking the thread as "Closed"

Is there any way to throw an error in log like "API not responding" when API gives 40* error?
Easier and faster to debug, of course i could have checked if my app was working but i was convinced it was the update :)
