### ISSUE TITLE
Speed and Energy consumption

### ISSUE THREAD

**Issue by GrmpfNarf** [mitch-dc/volkswagen_we_connect_id#183]
Hello everybody,
**Describe the solution you'd like**
is there any way to get the current speed and/or energy consumption while driving? Why I need this I described below. These two values could be integrated into the Device Tracker like the speed Attribute from a Smartphone device tracker. 

**Additional context**
I‘m trying to use the API from „A Better Route Planer“ with the data from your integration. This works Fine so far but would be better when these two values can be also transmitted. 

Thanks in advance.

**Comment by mitch-dc** [comment]
The api does not provide these values, even the location is only updated when the car is parked. 
If you want to use ABRP you can try to use an OBD dongle.
