### ISSUE TITLE
System crashes

### ISSUE THREAD

**Issue by gkrallo** [mitch-dc/volkswagen_we_connect_id#19]
version 0.0.8.5
The RPi repeatvely chrash when I have the integration activated
After a restart it works fine for a while but- suddenly the system freez I se that the load get up badly ( very high)

After a couple of hours it start again

<img width="827" alt="processor_use" src="https://user-images.githubusercontent.com/96731141/155896687-3b5a6117-7157-46c7-aa97-3cc23d7065d0.png">
<img width="830" alt="load" src="https://user-images.githubusercontent.com/96731141/155896692-e1a795f4-bd06-4d5a-a483-fdbbd14b0d28.png">

**Comment by BugBasher28** [comment]
Looks like the problems I have, see #8

**Comment by mitch-dc** [comment]
double
