### ISSUE TITLE
Configuration - username and password

### ISSUE THREAD

**Issue by georg-sch** [mitch-dc/volkswagen_we_connect_id#20]
More a request for help, rather than an issue (but I didn't find any discussion forum hereunder)

When I integrate the Volkswagen WeConnect ID Integration into my HACS, according to the Configuration paragraph it is stated: " _After that enable the integration on the integration page in Home Assistant with your e-mail and password that you use to login into the app_"

But nothing shows up anywhere - or I am not able to locate it. Where do I find the form to enter my username and password?
Alternatively: Can I edit some files directly, to enter username and password there?

**Comment by mitch-dc** [comment]
Try restart home assistant?
