### ISSUE TITLE
Change charging current from the car side

### ISSUE THREAD

**Issue by vellur** [mitch-dc/volkswagen_we_connect_id#23]
**Is your feature request related to a problem? Please describe.**

Possibility to start/stop charging, or adjust current intake from the car side.

**Describe the solution you'd like**
Possibility to change charging power from HA, Ie. Start/Stop/ in amperes/how ever is stated :)

I'm not owning VW ID family car yet, but im thinking solutions for my home load balancing solutions. I dont even know if this is possible... :)

If I can change charging modes from HA and car side, I would only need stupid charger and car and HA will decide when I can charge and what speed. I might have other appliances on at the same time like. Sauna (8kW), Stove (2-4kW?) etc. Now i can measure my home electric usage. It should be quite straight forward to change maximum output to the car if that is changeable from VW side.

**Comment by mitch-dc** [comment]
You can already start/stop the charging. 

And VW only has the option to 'reduce' charge speed it will charge at 50% of it's max charging power.

**Comment by vellur** [comment]
Ah, Good to know because it wasn't stated in the fronpage,  only "Start climatization in your Volkswagen ID car." as stated as button and others in sensor.
