### ISSUE TITLE
Can't find this integration in HACS...?

### ISSUE THREAD

**Issue by OZ1SEJ** [mitch-dc/volkswagen_we_connect_id#234]
In HACS, if I search for "VW", "Volkswagen", "We Connect" or "we_connect" - I just don't see anything. Am I doing something wrong?

**Comment by TheSentinel0101** [comment]
Probably your hacs filter has selected the downloaded plugins.

**Comment by OZ1SEJ** [comment]
Thank you. I'm clearly a rookie.
