### ISSUE TITLE
HACS setup link not working

### ISSUE THREAD

**Issue by sborowy** [mitch-dc/volkswagen_we_connect_id#257]
Hi there!

I tried using the Link provided in the description (https://custom-components.github.io/hacs/) to install the add-on. Unfortunately it seems to be broken.
Did anyone stumble upon this as well?

Best
Silas

**Comment by michaelarnauts** [comment]
You'll need to add this repo to HACS first. See https://github.com/mitch-dc/volkswagen_we_connect_id?tab=readme-ov-file#hacs

**Comment by celik75** [comment]
> You'll need to add this repo to HACS first. See https://github.com/mitch-dc/volkswagen_we_connect_id?tab=readme-ov-file#hacs

please tell how, the link is dead!

**Comment by pdcastro** [comment]
@celik75, the new link for HACS (Home Assistant Community Store) is https://hacs.xyz. If you do not have HACS installed yet, first install HACS following the instructions on that website. After HACS is installed, use the HACS tab in your Home Assistant dashboard (your local server) to install the Volkswagen We Connect ID integration as a [custom repository](https://hacs.xyz/docs/faq/custom_repositories). I believe the custom repository URL would be `https://github.com/mitch-dc/volkswagen_we_connect_id/`.
