### ISSUE TITLE
Vehicle total milage not changing

### ISSUE THREAD

**Issue by dward32** [mitch-dc/volkswagen_we_connect_id#268]
I have noticed that my vehicle total milage hasn't change in many months... any one else noticed this? The rest of the data is correct and is up to date. Thanks

**Comment by pdcastro** [comment]
If you mean the entity named `sensor.<my_id_3>_odometer`, mine is updating normally:

<img height="360" src="https://github.com/user-attachments/assets/638ed4dd-0318-47dc-8dca-ce53bb333b63" />

(The gap in the middle is OK – the server was intentionally shut down.)

Volkswagen We Connect ID **version 0.2.3**
Home Assistant **version 2024.7.4**

**Comment by dward32** [comment]
How strange.. for some reason my milage stops at the end of January...

<img width="839" alt="Screenshot 2024-07-31 at 16 11 55" src="https://github.com/user-attachments/assets/fbfa5ec2-22e7-4b07-8100-661b86e80d7a">

**Comment by dward32** [comment]
So I've installed a fresh Home assistant on a separate PC and installed the integration... still the same 31765km... which isn't the cars odometer reading! I don't get why...

**Comment by pdcastro** [comment]
> _[...] which isn't the cars odometer reading!_

Does the official Android / iOS Volkswagen app show the same mileage as the car’s odometer, or is it also stuck at 31,765km?

In my case with an ID.3 and the Volkswagen app for Android (v3.17.0 downloaded from the Google Play Store), the initial app screen has a **Vehicle Health Report** link that leads to another screen that shows the same mileage shown in Home Assistant, and the car.

**Comment by dward32** [comment]
im using the iPhone app and it doesn't show mileage.. unfortunately

**Comment by dward32** [comment]
I've just loaded another app on my phone celled evvee, this links to the VW servers and its showing my milage to be 19738miles which is 31765 KM, so clearly this is an issue on VW side.

**Comment by dward32** [comment]
ok, its a known problem having just googled it.. synchronised it with the car and now showing correct mileage. sorry for the NON issue!
