### ISSUE TITLE
Failed to set up after updating HA to 2024.9.1

### ISSUE THREAD

**Issue by markbw999** [mitch-dc/volkswagen_we_connect_id#270]
I got back from holiday a couple of days ago with lots of pending updates in HA. Our car was at home and had gone offline while we where away but your integration was still showing the last values it had received from the VW api. However, once I updated HA to 2024.9.1 your VW integration shows "Failed to set up" and all the entities are unavailable. I have tried reloading the integration a couple of times and rebooting HA but it doesn't make any difference. Is there a compatibility issue with the latest version of HA?

**Comment by jaket91-1** [comment]
I'm seeing the same after upgrading to HA 2024.9.1. The error I'm seeing in the debug log is as below

```bash
weconnect.errors.APICompatibilityError: No user id provided. A possible reason is that you have to reconfirm the terms and conditions.
```

**Comment by jaket91-1** [comment]
Ah, [this](https://github.com/mitch-dc/volkswagen_we_connect_id/issues/158#issuecomment-1453731882) previous post on an issue in this repo regarding the same problem solved it for me, logging onto volkswagen.co.uk there were some T&C's to accept. Reloading after that fixed it.

**Comment by markbw999** [comment]
Thank you so much! That's fixed it.
