### ISSUE TITLE
Please add ID7 Tourer

### ISSUE THREAD

**Issue by AgentP38** [mitch-dc/volkswagen_we_connect_id#271]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by flame4ever** [comment]
I have added it, but it still needs to be checked:
https://github.com/mitch-dc/volkswagen_we_connect_id/pull/273
You can also build it into you integration yourself, just go to config\custom_components\volkswagen_we_connect_id\__init__.py and adjust line 36 as follows "SUPPORTED_VEHICLES = ["ID.3", "ID.4", "ID.5", "ID. Buzz", "ID.7 Limousine", "ID.7 Tourer"]". 
Then restart HA.

**Comment by flame4ever** [comment]
#273

**Comment by AgentP38** [comment]
Thanks a lot my car will come next month then I will try out and give feedback...

**Comment by flame4ever** [comment]
I have now switched to https://github.com/robinostlund/homeassistant-volkswagencarnet, it supports ID7 and is being further developed.
