### ISSUE TITLE
[Feauture Request] More Configuration Options

### ISSUE THREAD

**Issue by Maxi531** [mitch-dc/volkswagen_we_connect_id#28]
Is it possible to add these options: 
1. Reduce AC charging current    -- "on" & "off"
2. Automatically Release AC cable    -- "on" & "off"
3. Auxiliary air conditioning    -- "on" & "off"
4. Automatic Window Heating    -- "on" & "off"
5. Zones    -- options are "Front Left" & "Front Right" as seperate toggles

These options are available in the VW ID App, would be awesome to be able to control them through HA as well.

**Comment by mitch-dc** [comment]
1. Is already available!

Will look into the others soon.
