### ISSUE TITLE
device tracker support

### ISSUE THREAD

**Issue by robinostlund** [mitch-dc/volkswagen_we_connect_id#34]
Hi,
Want to start with saying thanks for your custom component.
I am wondering if it would be possible to add a device_tracker to it as v3 of the firmware allows the end user to enable position data to be sent to we connect. And i have checked with the owner of the weconnect-python module that it supports it, and i can see it is set to : 
   self.latitude: Optional[float] = None
   self.longitude: Optional[float] = None
https://github.com/tillsteinbach/WeConnect-python/issues/60
https://github.com/tillsteinbach/WeConnect-python/blob/main/weconnect/elements/parking_position.py

I have created this in my component for the old we connect: https://github.com/robinostlund/homeassistant-volkswagencarnet if you want to have something to refer to :)

Brg
Robin

**Comment by mitch-dc** [comment]
Added in beta version
