### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by torge70** [mitch-dc/volkswagen_we_connect_id#42]
Hi, 
I am not able to find this integration in HACS?
The only we connect integration i can findis for older VW cars.

What am I doing wrong?

**Comment by BugBasher28** [comment]
You need to add this repository as a Custom Repository:
![image](https://user-images.githubusercontent.com/78534014/177949314-bf536492-eb9f-46b6-ae9f-b03ea9f0eb8c.png)
Repository: https://github.com/mitch-dc/volkswagen_we_connect_id
Category: Integration

**Comment by torge70** [comment]
Thanks. Didn't understand that part of the installation instructions.
