### ISSUE TITLE
Cannot add integration

### ISSUE THREAD

**Issue by nikkilocke** [mitch-dc/volkswagen_we_connect_id#45]
## Version of the custom_component
0.0.11 installed from git today

## Installation method (hacs / manual)
HACS custom repository

## Describe the bug

I accidentally installed the ordinary WeConnect app, and tried to add it in HA Settings/Integrations, before reading that I need to install this one as a custom component.

Now I have installed it as a custom component using HACS, but it doesn't appear on the list of Integrations to install in Settings/Integrations. (I have restarted HA multiple times, to make sure.)

The folder is there on the server

HACS list of installed components
![image](https://user-images.githubusercontent.com/684025/178707950-1ff857af-f259-4f80-8be3-1ec6f013ee36.png)

List of integrations I can add in Settings/Integrations
![image](https://user-images.githubusercontent.com/684025/178708158-49ed06fb-b751-4cd8-bb17-10543b67115c.png)

```
# ls -la config/custom_components/
total 8
drwxr-xr-x 7 root root  114 Jul 13 11:05 .
drwxr-xr-x 9 root root 4096 Jul 13 10:50 ..
drwxr-xr-x 8 root root 4096 Jul 13 11:01 hacs
drwxr-xr-x 4 root root  212 Jul 13 10:28 myenergi
drwxr-xr-x 4 root root  194 Jun  2 21:23 solaredge_modbus
drwxr-xr-x 3 root root  311 Jul 13 10:01 volkswagencarnet
drwxr-xr-x 3 root root  220 Jul 13 10:42 volkswagen_we_connect_id
```

**Comment by tsg21** [comment]
You need to install this repo as a custom repository in the HACS UI. Click the three dots icon at the top right of the HACS "integrations" view, then add https://github.com/mitch-dc/volkswagen_we_connect_id

**Comment by nikkilocke** [comment]
I did exactly that - how else could I have got it to appear on the HACS list?

**Comment by gluca** [comment]
i have the same problem. I removed the NON ID we conenct integration, installed the custom repo with hack from github, restarted, the inegration is listed in hacs among others but when i search for the integration in integration panel it find nothing
