### ISSUE TITLE
Binary Sensors missing

### ISSUE THREAD

**Issue by ColinRobbins** [mitch-dc/volkswagen_we_connect_id#47]
Two `binary_sensors` that were working, are now showing as `unavailable`.
The sensors are:
* `binary_sensor.ev_car_is_online`
* `binary_sensor.ev_car_is_active`

## Version of the custom_component

0.0.12.

## Installation method (hacs / manual)
HACS

## Configuration

```yaml

Add your configuration here.

```

## Describe the bug

They were working until about 18:00 last night.   When they stopped working I upgraded to 0.0.12.
Looks like the latest code base removes them?

## Debug log

```text

Add your logs here.

```

**Comment by mitch-dc** [comment]
These sensors made the integration crash because they are no longer available in the api. 
So i've removed them.

**Comment by ColinRobbins** [comment]
That’s disappointing,
Do you know if this is a temporary or permanent change to the API?

**Comment by ColinRobbins** [comment]
Superseded, can now be closed.
