### ISSUE TITLE
Problem with binary sensors

### ISSUE THREAD

**Issue by skvist60** [mitch-dc/volkswagen_we_connect_id#5]
Hi,

Thank you for creating this very nice integration! :)

I have been using it for about 24h now, and I get lots of these errors in the log:

> 
> 2022-01-30 20:38:35 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform volkswagen_we_connect_id
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
> await asyncio.gather(*tasks)
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
> await entity.add_to_platform_finish()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
> self.async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
> self._async_write_ha_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
> state = self._stringify_state()
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
> if (state := self.state) is None:
> File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 205, in state
> return STATE_ON if self.is_on else STATE_OFF
> File "/config/custom_components/volkswagen_we_connect_id/binary_sensor.py", line 163, in is_on
> return state == self.entity_description.on_value.value
> File "/usr/local/lib/python3.9/enum.py", line 429, in __getattr__
> raise AttributeError(name) from None
> AttributeError: value

I'm not sure about this, but looking in the code it looks to me like the previous fix for some binary sensors were undone when the login problem was fixed.

**Comment by mitch-dc** [comment]
Will take a look on it after work today!

**Comment by woutercoppens** [comment]
![image](https://user-images.githubusercontent.com/7490279/151766876-a31ddf33-9f50-40ef-8a55-6aeb3672735b.png)

**Comment by mitch-dc** [comment]
Fixed in latest version
https://github.com/mitch-dc/volkswagen_we_connect_id/releases/tag/v0.0.6.3
