### ISSUE TITLE
TargetSoCNumber is overriding deprecated methods on an instance of NumberEntity

### ISSUE THREAD

**Issue by ColinRobbins** [mitch-dc/volkswagen_we_connect_id#50]
Re-opening (https://github.com/mitch-dc/volkswagen_we_connect_id/issues/35), as fix has not solved the issue

## Version of the custom_component

0.0.12

## Installation method (hacs / manual)
HACS

## Installation method of hass (venv, docker, hassio,...)
Venv

## Debug log

```text

Logger: homeassistant.components.number
Source: components/number/__init__.py:220
Integration: Number (documentation, issues)
First occurred: 20 July 2022 at 18:27:24 (2 occurrences)
Last logged: 20 July 2022 at 18:27:24

custom_components.volkswagen_we_connect_id.number::TargetSoCNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.
custom_components.volkswagen_we_connect_id.number::TargetClimateNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom component author.

```

**Comment by mitch-dc** [comment]
Did you update? I don't have these error logs in the latest version of Hass and integration

**Comment by ColinRobbins** [comment]
Yes, I am using HACS, and it says version `v0.0.12`

**Comment by ColinRobbins** [comment]
Manifest,Json says 0.6

**Comment by ColinRobbins** [comment]
WeConnect, 0.45

**Comment by ColinRobbins** [comment]
Tracing this, the error comes from [homeassistant/components/number/__init__.py](https://github.com/home-assistant/core/blob/dev/homeassistant/components/number/__init__.py#L211) where the following are no longer supported.

```
                "async_set_value",
                "max_value",
                "min_value",
                "set_value",
                "step",
                "unit_of_measurement",
                "value",
```
In this interation [number.py](https://github.com/mitch-dc/volkswagen_we_connect_id/blob/main/custom_components/volkswagen_we_connect_id/number.py#L61) has a `value` method.

Not sure what the solution is.
