### ISSUE TITLE
VW API unstable 

### ISSUE THREAD

**Issue by ColinRobbins** [mitch-dc/volkswagen_we_connect_id#55]
The upstream API seems rather unstable, with some attributes not always available.
This can cause this component to fail to load on occasions.

## Version of the custom_component

0.0.12

## Installation method (hacs / manual)

HACS

## Installation method of hass (venv, docker, hassio,...)

Venv

## Describe the bug

Can I gets the code to calculate an attribute value is wrapped with:

```text
  try:
        do the calc
  except KeyError:
        return None.

```

**Comment by mitch-dc** [comment]
At this moment the API is not updating anything for my car :P 
So it's difficult to test this, but i dont really like adding try catches everywhere. But it looks like it's the only way now.
