### ISSUE TITLE
Incorrect state class for charging state

### ISSUE THREAD

**Issue by ColinRobbins** [mitch-dc/volkswagen_we_connect_id#60]
## Version of the custom_component

0.0.12

## Installation method (hacs / manual)
HACS

## Installation method of hass (venv, docker, hassio,...)
Venv

## Describe the bug

`sensor.py` defaults everything to a state class of measurement.
This is only appropriate for sensors that return a numeric state.
Thus, it is incorrect for the charge state sensor which returns a string.

The impact is the sensor does not correct show in history.

**Comment by pplucky** [comment]
Should be solved by [#81](https://github.com/mitch-dc/volkswagen_we_connect_id/pull/81)
