### ISSUE TITLE
Unit "km/h" is not a matching unit for an entity in the entity class 'power'

### ISSUE THREAD

**Issue by CodeMusher** [mitch-dc/volkswagen_we_connect_id#61]
## Version of the custom_component
0.0.12

## Installation method (hacs / manual)
HACS

## Installation method of hass (venv, docker, hassio,...)
HASSOS

## Configuration

```yaml

Add your configuration here.

```

## Describe the bug

sensor.xxx_charge_rate has an issue. The unit ("km/h") for the entity does not match an entity in the entity class 'power'

## Debug log

```text

Add your logs here.

```

**Comment by mitch-dc** [comment]
Fixed in next release
