### ISSUE TITLE
Unknown error during setup

### ISSUE THREAD

**Issue by conradhagemans** [mitch-dc/volkswagen_we_connect_id#62]
![DCA157F6-1008-4AAF-90D2-C8B3D032C08E](https://user-images.githubusercontent.com/9007177/184026519-329633ab-9229-4f2b-9573-2a8c9e32604c.jpeg)
I tried to install the integration using HACS.
After installation I add the integration.
Insert username and password.
Then I get Unknown error occurs. 

I am on HA 2022.8.3 running in docker.
I have plenty other integrations including from HACS

**Comment by hassio40** [comment]
I was using the Android application We Connect ID and I had made all the registrations from the application
Instead, you must explicitly accept the terms of contract and service that appear by going to the myvolkswagen.de site even if you are from other countries such as Italy in my case.
After that the integration works perfectly

**Comment by conradhagemans** [comment]
Thanks. I confirmed on the VW website. Still same problem. I think it has to do something with my installation. Maybe I cannot connect to the VW server from within docker.
