### ISSUE TITLE
Feature Request: Add trip values

### ISSUE THREAD

**Issue by flixlix** [mitch-dc/volkswagen_we_connect_id#63]
**Is your feature request related to a problem? Please describe.**
Is it possible to add trip values such as average consumption, average speed, etc. over the three different periods the car shows?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DarkFox** [comment]
As far as I'm aware, those values are not exposed (or even collected) by VW, presumably due to privacy concerns.
