### ISSUE TITLE
Missing data in my setup.

### ISSUE THREAD

**Issue by PeterAndreS** [mitch-dc/volkswagen_we_connect_id#69]
Never have i ever seen expected values from following sensors.   (Always Unknown!)

- **Sensor**         >>                           **Value**
- ID4 odometer_in_kilometers     >>       Unknown
- ID4 tracker                         >>              Unknown

v0.0.13
We Connect ID (2.2.21) on android
ID.4 software 2.4-(Dealer updated) (Actual 2.3)

HACS

hassio

yaml

```

I always gets the value Unkown from odometer and tracker.
Expected sum of km and gps location.

I Guess it is not supported before Id SW 3.0?

## Debug log

None relevant i guess.

```

**Comment by mitch-dc** [comment]
You need to wait to 3.0 :(
