### ISSUE TITLE
State of Charge missing

### ISSUE THREAD

**Issue by dward32** [mitch-dc/volkswagen_we_connect_id#74]
We used to get state of charge ie. 80% but this Is no longer given, can you check to see if there is an issue? Thanks

**Comment by mitch-dc** [comment]
There are no issues at the moment, maby the VW API had some downtime?

**Comment by dward32** [comment]
I am still getting it showing as unavailable.. see below.. any thoughts on why?

Thanks
Dean


<img width="688" alt="Screenshot 2022-10-21 at 15 51 58" src="https://user-images.githubusercontent.com/77810867/197225210-ccbee24c-e849-471d-ae56-ff0f1ef2e912.png">

**Comment by mitch-dc** [comment]
I think you should readd the integration, i can't reproduce this issue. Maby it's disabled or something in your HA instance
