### ISSUE TITLE
Device tracker shows: unknown

### ISSUE THREAD

**Issue by peerkn** [mitch-dc/volkswagen_we_connect_id#75]
Version of the custom_component: 0.0.13

Installation method hacs

Installation method of hass:  hassio

Configuration:

add device

Describe the bug:

A clear and concise description of what the bug is:

Device tracker shows: unknown

Debug log no entries

GPS is activated and i get the place from ID3 in the App

What i´m doing wrong?

Thanks

Peer

**Comment by mitch-dc** [comment]
Do you have 3.0+ installed on your cars infotainment system?

**Comment by peerkn** [comment]
Thank you for your answer.
I have Version 2.4.
Best regards
Peer Knoth

Mitch ***@***.***> schrieb am Sa., 22. Okt. 2022, 20:26:
