### ISSUE TITLE
Bump HACS version

### ISSUE THREAD

**Issue by ColinRobbins** [mitch-dc/volkswagen_we_connect_id#86]
Could you please update the release version from 0.0.13.
Via HACS we don't get all the good updates since July.

**Comment by pplucky** [comment]
Without disagreeing this could make sense (aside from the current binary sensor issues), you can always re-download the integration via HACS and choose main:
![image](https://user-images.githubusercontent.com/16407309/199423448-c1239e6a-2470-4ecb-95d3-ddb11220c2d7.png)

> Via HACS we don't get all the good updates since July.

Above installation method will...
