### ISSUE TITLE
"Car is active" binary sensor is not corrrect

### ISSUE THREAD

**Issue by ColinRobbins** [mitch-dc/volkswagen_we_connect_id#87]
## Version of the custom_component

0.0.13
## Installation method (hacs / manual)
HACS

## Installation method of hass (venv, docker, hassio,...)
Venv

## Configuration

Default, via config

## Describe the bug

The sensor `binary_sensor.XXX_car_is_active` is always showing `true`.

## Debug log

Using the python library, I've looked at the domain and it shows...

```
[readiness] Elements: 1 items
	[readinessStatus]
		Connection State: 
			Is online: True
			Battery power level: comfort
			Daily Power Budget Available: True 
```
I.e., The "Is Active" parameter does not appear to be there.

The sensor appears to be returning the previous value.
Would it be more appropriate to return `None`?

**Comment by pplucky** [comment]
That doesn't happen to me with latest release 0.0.13, but with the latest changes in the repo - check #82

**Comment by mitch-dc** [comment]
Tested it after latest release and it's fixed :)

**Comment by ColinRobbins** [comment]
Upgrade to the latest, and it’s still always showing “on” here.

**Comment by pplucky** [comment]
> Upgrade to the latest, and it’s still always showing “on” here.

Same here, already reported via #82 to be reopened.
