### ISSUE TITLE
Not able to load the integration since version 0.0.14

### ISSUE THREAD

**Issue by renslinden** [mitch-dc/volkswagen_we_connect_id#89]
## Version of the custom_component

0.0.14

## Installation method (hacs / manual)
HACS

## Installation method of hass (venv, docker, hassio,...)
Docker

## Configuration
 N/A

## Describe the bug
I'm not able to load the integration anymore. Tried many restarts.
Don't know the exact reason, the official ID Connect application is working fine.
Happened to me since I installed the latest version of this integration yesterday.

## Debug log

```text
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:253
Integration: Binaire sensor (documentation, issues)
First occurred: 18:48:56 (4 occurrences)
Last logged: 19:54:59

Setup of platform volkswagen_we_connect_id is taking longer than 60 seconds. Startup will proceed without waiting any longer.
```

Startup result:

```text
Logger: homeassistant
Source: custom_components/volkswagen_we_connect_id/binary_sensor.py:155
Integration: Volkswagen We Connect ID (documentation)
First occurred: 18:49:56 (4 occurrences)
Last logged: 19:55:59

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/volkswagen_we_connect_id/binary_sensor.py", line 155, in async_setup_entry
    for index, vehicle in enumerate(coordinator.data):
TypeError: 'NoneType' object is not iterable
```

**Comment by mnorrsken** [comment]
I got the same issue, dropping to 0.0.13 fixed the problem

**Comment by renslinden** [comment]
> I got the same issue, dropping to 0.0.13 fixed the problem

How can i revert to version 0.0.13?

**Comment by renslinden** [comment]
Nevermind found it already.

HACS > Select integration > 3 dots upper corner > Download again > Select specific version

**Comment by mnorrsken** [comment]
It's not completed however. 0.0.14 still doesn't work. The temporary solution was to downgrade to 0.0.13. I havnt had time to research what the problem with 0.0.14 is exactly, but I hope I can find some time this weekend.

**Comment by renslinden** [comment]
> It's not completed however. 0.0.14 still doesn't work. The temporary solution was to downgrade to 0.0.13. I havnt had time to research what the problem with 0.0.14 is exactly, but I hope I can find some time this weekend. I'm wondering if it's because our cars havnt been updated to version 3 yet.

See my comment [here](https://github.com/mitch-dc/volkswagen_we_connect_id/issues/85#issuecomment-1307843032)
