### ISSUE TITLE
Car locked status incorrect

### ISSUE THREAD

**Issue by vantech14** [mitch-dc/volkswagen_we_connect_id#90]
The car door lock status is incorrect. The official ID app doesnt show this parameter (like many others) however the status shows as "locked" constantly despite the car being unlocked. 

Thanks.

**Comment by pplucky** [comment]
You need to bare in mind that you need v3.x of the id software to be able to get this information. Do you?
<img width="624" alt="image" src="https://user-images.githubusercontent.com/16407309/200087104-431cd664-59c2-4adf-a55d-b55b78cd7ea3.png">

Looking at the official ID app, this indicates the lock status (the lock on top left and a different car picture showing which door is open):
![image](https://user-images.githubusercontent.com/16407309/200087589-037ad431-b69e-472f-9d25-f98738694887.png)

Still then, you also need to bare in mind that opening/closing doors can be too fast to be fetched and communicated to the API before the status changes back, so not all status changes will ever be fetched by HA.

I would see this as more useful for when you leave the doors open for too long, possibly unattended.

**Comment by vantech14** [comment]
My car went into the garage, for a software update of some description (the garage didn’t know what it was for to be honest) and since I’ve been waiting for a OTT download for more features.

How did you get to version 3? The garage or OTT?

Thanks.

Sent from my iPhone
________________________________

**Comment by pplucky** [comment]
> My car went into the garage, for a software update of some description (the garage didn’t know what it was for to be honest) and since I’ve been waiting for a OTT download for more features. How did you get to version 3? The garage or OTT? Thanks.
> […](#)



> How did you get to version 3? The garage or OTT?

Mine came with 3.1 from factory, got it less than a month ago.

**Comment by mitch-dc** [comment]
Will try to fix it, but further discussion will be here: 
https://github.com/mitch-dc/volkswagen_we_connect_id/issues/73
