### ISSUE TITLE
MyVW - Make it work with US based VW ID4

### ISSUE THREAD

**Issue by dresslerc** [mitch-dc/volkswagen_we_connect_id#91]
**Is your feature request related to a problem? Please describe.**
I am in USA and have a ID4.  I have my MyVW app setup and it works.  However, this plug in doesnt work.  I think the apps are different for US vs Non-US

**Comment by mitch-dc** [comment]
There is a whole different API and app for the USA. 
I can't build it because i live in the EU :( it's sad that VW choose to do this.
