### ISSUE TITLE
Device tracker is missing after upgrade to v0.1.0.1

### ISSUE THREAD

**Issue by whohencode** [mitch-dc/volkswagen_we_connect_id#94]
Looks like the device tracker is removed, is this a reason for this or can it be brought back?

device_tracker.id_5_pro_performance_tracker

This entity is no longer being provided by the volkswagen_we_connect_id integration. If the entity is no longer in use, delete it in settings.

**Comment by whohencode** [comment]
Checked the coded and it looks like that the device tracker is there, not showing up for me. Will continue troubleshooting.

**Comment by robinostlund** [comment]
Also removed for me :)

**Comment by pplucky** [comment]
Fixed in https://github.com/mitch-dc/volkswagen_we_connect_id/commit/4116e786b184c1d0b5febd89ca01d3f9acb09461, try updating to main.

**Comment by whohencode** [comment]
In the latest commit the code is still commented. Doesn´t matter if you re-install.

**Comment by pplucky** [comment]
> In the latest commit the code is still commented. Doesn´t matter if you re-install.

That's why I said I manually removed the comment from the file in the custom components folder, for testing purposes... and it seems to be working.

**Comment by mitch-dc** [comment]
i've added it again
