### ISSUE TITLE
Front right door is missing

### ISSUE THREAD

**Issue by robinostlund** [mitch-dc/volkswagen_we_connect_id#95]
Looks like front right door is missing:
Entity not available: sensor.id_5_gtx_door_front_right_lock_status

**Comment by pplucky** [comment]
> Looks like front right door is missing: Entity not available: sensor.id_5_gtx_door_front_right_lock_status

Maybe related to the fact that we have a Right Left Open + Lock Status?
![image](https://user-images.githubusercontent.com/16407309/202205136-aac9e0d7-c837-4e85-bed6-e18b75bd5bae.png)

**Comment by robinostlund** [comment]
Yeap, seems like a typo? :)

**Comment by pplucky** [comment]
Solved by #93 ?
